language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6

sudo: false

before_install:
  - gem update --system
  - gem install bundler

install:
  - bundle install

script:
  - rake test

matrix:
  allow_failures:
    - rvm: 2.6

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
