module XRay
  # AWS Services listed below will be recorded as subsegments
  module AwsServices
    # exausted list can be tracked at http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Seahorse/Client/Base.html
    @whitelist = %I[
      ACM
      APIGateway
      AlexaForBusiness
      AppStream
      AppSync
      ApplicationAutoScaling
      ApplicationDiscoveryService
      Athena
      AutoScaling
      Batch
      Budgets
      Cloud9
      CloudDirectory
      CloudFormatioin
      CloudFront
      CloudHSM
      CloudHSMV2
      CloudSearch
      CloudSearchDomain
      CloudTrail
      CloudWatch
      CloudWatchEvents
      CloudWatchLogs
      CodeBuild
      CodeCommit
      CodeDeploy
      CodePipeline
      CodeStar
      CognitoIdentity
      CognitoIdentityProvider
      CognitoSync
      Comprehend
      ConfigService
      CostExplore
      CostandUsageReportService
      DAX
      DataPipeline
      DatabaseMigrationService
      DeviceFarm
      DirectConnect
      DirectoryService
      DynamoDB
      DynamoDBStreams
      EC2
      ECR
      ECS
      EFS
      EMR
      ElastiCache
      ElasticBeanstalk
      ElasticLoadBalancing
      ElasticLoadBalancingV2
      ElasticTranscoder
      ElasticsearchService
      Firehose
      GameLift
      Glacier
      Glue
      Greengrass
      GuardDuty
      Health
      IAM
      ImportExport
      Inspector
      IoT
      IoTDataPlane
      IoTJobsDataPlane
      KMS
      Kinesis
      KinesisAnalytics
      KinesisVideo
      KinesisVideoArchiveMedia
      KinesisVideoMedia
      Lambda
      LambdaPreview
      Lex
      LexModelBuildingService
      LexRuntimeService
      Lightsail
      MQ
      MTurk
      MachineLearning
      MarketplaceCommerceAnalytics
      MarketplaceEntitlementService
      MarketplaceMetering
      MediaConvert
      MediaLive
      MediaPackage
      MediaStore
      MediaStoreData
      MigrationHub
      Mobile
      OpsWorks
      OpsWorksCM
      Organizations
      Pinpoint
      Polly
      Pricing
      RDS
      Redshift
      Rekognition
      ResourceGroups
      ResourceGroupsTaggingAPI
      Route53
      Route53Domains
      S3
      SES
      SFN
      SMS
      SNS
      SQS
      SSM
      STS
      SWF
      SageMaker
      SageMakerRuntime
      ServerlessApplicationRepository
      ServiceCatalog
      ServiceDiscovery
      Shield
      SimpleDB
      Snowball
      States
      StorageGateway
      Support
      Translate
      WAF
      WAFRegional
      WorkDocs
      WorkSpaces
      XRay
    ]

    def self.whitelist
      @whitelist
    end

    def self.whitelist=(v)
      @whitelist = v
    end
  end
end
