name: Continuous monitoring of distribution channels
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

permissions:
  id-token: write
  contents: read

jobs:
  smoke-tests:
    name: Run smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2.7.0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a #v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_INTEG_TEST_ROLE_ARN }}
          aws-region: us-east-1
      
      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f #v1.295.0
        with:
          ruby-version: 2.7
        env:
          TEST_DISTRIBUTION: true
      
      - name: Install dependencies
        run: bundle install
        env:
          TEST_DISTRIBUTION: true
      
      - name: Run distribution test
        id: distribution-availability
        run: bundle exec rake test_distribution
        env:
          TEST_DISTRIBUTION: true
          
      - name: Publish metric on X-Ray Ruby SDK distribution availability
        if: ${{ always() }}
        run: |
          if [[ "${{ steps.distribution-availability.outcome }}" == "failure" ]]; then
            aws cloudwatch put-metric-data --metric-name XRayRubySDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 1 --timestamp $(date +%s)
          else
            aws cloudwatch put-metric-data --metric-name XRayRubySDKDistributionUnavailability --dimensions failure=rate --namespace MonitorSDK --value 0 --timestamp $(date +%s)
          fi
